#cloud-config
# Modify this file to include your keys, unit, configuration ....
# Have a look at https://github.com/coreos/coreos-cloudinit

hostname: usbkey.drewfus.org

write_files:
  - path: "/etc/resolv.conf"
    permissions: "0644"
    owner: "root"
    content: |
      nameserver 8.8.8.8
  - path: "/etc/motd"
    permissions: "0644"
    owner: "root"
    content: |
      Good news, everyone!

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: "https://discovery.etcd.io/0eb75cd08d6a059da7550bb2075ac9f8"
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"

  flannel:
    etcd_prefix: "/coreos.com/drewfus.org"
    
  update:
    reboot-strategy: etcd-lock

  units:
    - name: etcd.service
      command: start
    - name: flannel.service
      command: start
